apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: arielrahamim/client-eks
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: client-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
data:
  serverHost: "addb1eb031c3e49f4a02c257deb08cd8-fe6536e4c6bab1ec.elb.eu-central-1.amazonaws.com"
  serverPort: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  # type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    # targetPort: 8080
    # nodePort: 30008
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 8080
